# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Fri Oct 12 15:31:31 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(825, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.catlist = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catlist.sizePolicy().hasHeightForWidth())
        self.catlist.setSizePolicy(sizePolicy)
        self.catlist.setBaseSize(QtCore.QSize(200, 500))
        self.catlist.setAlternatingRowColors(True)
        self.catlist.setRootIsDecorated(False)
        self.catlist.setAllColumnsShowFocus(True)
        self.catlist.setObjectName(_fromUtf8("catlist"))
        self.catlist.header().setDefaultSectionSize(100)
        self.revlist = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revlist.sizePolicy().hasHeightForWidth())
        self.revlist.setSizePolicy(sizePolicy)
        self.revlist.setBaseSize(QtCore.QSize(500, 500))
        self.revlist.setToolTip(_fromUtf8(""))
        self.revlist.setAlternatingRowColors(False)
        self.revlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.revlist.setRootIsDecorated(False)
        self.revlist.setObjectName(_fromUtf8("revlist"))
        self.revlist.header().setCascadingSectionResizes(False)
        self.revlist.header().setDefaultSectionSize(100)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSorting = QtWidgets.QMenu(self.menubar)
        self.menuSorting.setObjectName(_fromUtf8("menuSorting"))
        self.menuAssign = QtWidgets.QMenu(self.menubar)
        self.menuAssign.setObjectName(_fromUtf8("menuAssign"))
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenSpreadsheet = QtWidgets.QAction(MainWindow)
        self.actionOpenSpreadsheet.setObjectName(_fromUtf8("actionOpenSpreadsheet"))
        self.actionOpenSession = QtWidgets.QAction(MainWindow)
        self.actionOpenSession.setObjectName(_fromUtf8("actionOpenSession"))
        self.actionSaveSession = QtWidgets.QAction(MainWindow)
        self.actionSaveSession.setObjectName(_fromUtf8("actionSaveSession"))
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAssign = QtWidgets.QAction(MainWindow)
        self.actionAssign.setObjectName(_fromUtf8("actionAssign"))
        self.actionAssignAllReviewers = QtWidgets.QAction(MainWindow)
        self.actionAssignAllReviewers.setObjectName(_fromUtf8("actionAssignAllReviewers"))
        self.actionAssignReserves = QtWidgets.QAction(MainWindow)
        self.actionAssignReserves.setObjectName(_fromUtf8("actionAssignReserves"))
        self.actionClearAssignments = QtWidgets.QAction(MainWindow)
        self.actionClearAssignments.setObjectName(_fromUtf8("actionClearAssignments"))
        self.actionAssignAllLabels = QtWidgets.QAction(MainWindow)
        self.actionAssignAllLabels.setObjectName(_fromUtf8("actionAssignAllLabels"))
        self.actionAssignAllReviewCategories = QtWidgets.QAction(MainWindow)
        self.actionAssignAllReviewCategories.setObjectName(_fromUtf8("actionAssignAllReviewCategories"))
        self.actionAssignAllSubmissionCategories = QtWidgets.QAction(MainWindow)
        self.actionAssignAllSubmissionCategories.setObjectName(_fromUtf8("actionAssignAllSubmissionCategories"))
        self.actionAssignFirst = QtWidgets.QAction(MainWindow)
        self.actionAssignFirst.setObjectName(_fromUtf8("actionAssignFirst"))
        self.actionAssignSecond = QtWidgets.QAction(MainWindow)
        self.actionAssignSecond.setObjectName(_fromUtf8("actionAssignSecond"))
        self.actionAssignThird = QtWidgets.QAction(MainWindow)
        self.actionAssignThird.setObjectName(_fromUtf8("actionAssignThird"))
        self.actionAssignFourth = QtWidgets.QAction(MainWindow)
        self.actionAssignFourth.setObjectName(_fromUtf8("actionAssignFourth"))
        self.actionAssignFifth = QtWidgets.QAction(MainWindow)
        self.actionAssignFifth.setObjectName(_fromUtf8("actionAssignFifth"))
        self.actionReviewerChoice = QtWidgets.QAction(MainWindow)
        self.actionReviewerChoice.setCheckable(True)
        self.actionReviewerChoice.setChecked(True)
        self.actionReviewerChoice.setWhatsThis(_fromUtf8(""))
        self.actionReviewerChoice.setObjectName(_fromUtf8("actionReviewerChoice"))
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWorkflow = QtWidgets.QAction(MainWindow)
        self.actionWorkflow.setObjectName(_fromUtf8("actionWorkflow"))
        self.actionColorize = QtWidgets.QAction(MainWindow)
        self.actionColorize.setCheckable(True)
        self.actionColorize.setChecked(True)
        self.actionColorize.setObjectName(_fromUtf8("actionColorize"))
        self.actionAbstractLimit = QtWidgets.QAction(MainWindow)
        self.actionAbstractLimit.setObjectName(_fromUtf8("actionAbstractLimit"))
        self.actionAbstractLowerLimit = QtWidgets.QAction(MainWindow)
        self.actionAbstractLowerLimit.setObjectName(_fromUtf8("actionAbstractLowerLimit"))
        self.actionReviewerLimit = QtWidgets.QAction(MainWindow)
        self.actionReviewerLimit.setObjectName(_fromUtf8("actionReviewerLimit"))
        self.actionReviewerUpperLimit = QtWidgets.QAction(MainWindow)
        self.actionReviewerUpperLimit.setObjectName(_fromUtf8("actionReviewerUpperLimit"))
        self.menuFile.addAction(self.actionOpenSpreadsheet)
        self.menuFile.addAction(self.actionOpenSession)
        self.menuFile.addAction(self.actionSaveSession)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAssign.addAction(self.actionAssign)
        self.menuAssign.addAction(self.actionClearAssignments)
        self.menuAssign.addSeparator()
        self.menuAssign.addAction(self.actionAssignAllReviewers)
        self.menuAssign.addAction(self.actionAssignReserves)
        self.menuAssign.addSeparator()
        self.menuAssign.addAction(self.actionAssignAllLabels)
        self.menuAssign.addAction(self.actionAssignAllReviewCategories)
        self.menuAssign.addAction(self.actionAssignAllSubmissionCategories)
        self.menuAssign.addSeparator()
        self.menuAssign.addAction(self.actionAssignFirst)
        self.menuAssign.addAction(self.actionAssignSecond)
        self.menuAssign.addAction(self.actionAssignThird)
        self.menuAssign.addAction(self.actionAssignFourth)
        self.menuAssign.addAction(self.actionAssignFifth)
        self.menuSorting.addAction(self.actionReviewerLimit)
        self.menuSorting.addAction(self.actionReviewerUpperLimit)
        self.menuSorting.addAction(self.actionAbstractLowerLimit)
        self.menuSorting.addAction(self.actionAbstractLimit)
        self.menuSorting.addSeparator()
        self.menuSorting.addAction(self.actionReviewerChoice)
        self.menuSorting.addAction(self.actionColorize)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWorkflow)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSorting.menuAction())
        self.menubar.addAction(self.menuAssign.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None ))
        self.catlist.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "select a category to assign reviewers", None ))
        self.catlist.setSortingEnabled(True)
        self.catlist.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Category #", None ))
        self.catlist.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Category Title", None ))
        self.catlist.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "# of Abstracts", None ))
        self.catlist.headerItem().setText(3, QtWidgets.QApplication.translate("MainWindow", "# of Assigned Reviewers", None ))
        self.catlist.headerItem().setText(4, QtWidgets.QApplication.translate("MainWindow", "Pool Size", None ))
        self.catlist.headerItem().setText(5, QtWidgets.QApplication.translate("MainWindow", "Assigned Reviewers", None ))
        self.revlist.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "check reviewers to assign them to the selected category", None ))
        self.revlist.setSortingEnabled(True)
        self.revlist.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Member #", None ))
        self.revlist.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Type", None ))
        self.revlist.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "First", None ))
        self.revlist.headerItem().setText(3, QtWidgets.QApplication.translate("MainWindow", "Last", None ))
        self.revlist.headerItem().setText(4, QtWidgets.QApplication.translate("MainWindow", "Designation", None ))
        self.revlist.headerItem().setText(5, QtWidgets.QApplication.translate("MainWindow", "Institution", None ))
        self.revlist.headerItem().setText(6, QtWidgets.QApplication.translate("MainWindow", "Email", None ))
        self.revlist.headerItem().setText(7, QtWidgets.QApplication.translate("MainWindow", "Primary Training", None ))
        self.revlist.headerItem().setText(8, QtWidgets.QApplication.translate("MainWindow", "Pubmed", None ))
        self.revlist.headerItem().setText(9, QtWidgets.QApplication.translate("MainWindow", "Pubmed #", None ))
        self.revlist.headerItem().setText(10, QtWidgets.QApplication.translate("MainWindow", "Journal Articles", None ))
        self.revlist.headerItem().setText(11, QtWidgets.QApplication.translate("MainWindow", "Reviewed Previously", None ))
        self.revlist.headerItem().setText(12, QtWidgets.QApplication.translate("MainWindow", "Choice 1", None ))
        self.revlist.headerItem().setText(13, QtWidgets.QApplication.translate("MainWindow", "Choice 2", None ))
        self.revlist.headerItem().setText(14, QtWidgets.QApplication.translate("MainWindow", "Choice 3", None ))
        self.revlist.headerItem().setText(15, QtWidgets.QApplication.translate("MainWindow", "Choice 4", None ))
        self.revlist.headerItem().setText(16, QtWidgets.QApplication.translate("MainWindow", "Choice 5", None ))
        self.revlist.headerItem().setText(17, QtWidgets.QApplication.translate("MainWindow", "# of Assigned Abstracts", None ))
        self.revlist.headerItem().setText(18, QtWidgets.QApplication.translate("MainWindow", "Assigned Categories", None ))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None ))
        self.menuAssign.setTitle(QtWidgets.QApplication.translate("MainWindow", "Assign", None ))
        self.menuSorting.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None ))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None ))
        self.actionOpenSpreadsheet.setText(QtWidgets.QApplication.translate("MainWindow", "Open Spreadsheet (.xls)", None ))
        self.actionOpenSession.setText(QtWidgets.QApplication.translate("MainWindow", "Open Session (.mpc)", None ))
        self.actionSaveSession.setText(QtWidgets.QApplication.translate("MainWindow", "Save Session (.mpc)", None ))
        self.actionExport.setText(QtWidgets.QApplication.translate("MainWindow", "Export (.xls)", None ))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None ))
        self.actionAssign.setText(QtWidgets.QApplication.translate("MainWindow", "Assign", None ))
        self.actionClearAssignments.setText(QtWidgets.QApplication.translate("MainWindow", "Clear assignments", None ))
        self.actionAssignAllReviewers.setText(QtWidgets.QApplication.translate("MainWindow", "Assign all reviewers", None ))
        self.actionAssignReserves.setText(QtWidgets.QApplication.translate("MainWindow", "Assign reserves", None ))
        self.actionAssignAllLabels.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by label", None ))
        self.actionAssignAllReviewCategories.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by review category", None ))
        self.actionAssignAllSubmissionCategories.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by submission category", None ))
        self.actionAssignFirst.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by first label", None ))
        self.actionAssignSecond.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by second label", None ))
        self.actionAssignThird.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by third label", None ))
        self.actionAssignFourth.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by fourth label", None ))
        self.actionAssignFifth.setText(QtWidgets.QApplication.translate("MainWindow", "Assign by fifth label", None ))
        self.actionReviewerChoice.setText(QtWidgets.QApplication.translate("MainWindow", "Reviewer\'s Choice", None ))
        self.actionReviewerChoice.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reviewer\'s Choice", None ))
        self.actionReviewerChoice.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "sort based off of the reviwer\'s top 5 category choices", None ))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None ))
        self.actionWorkflow.setText(QtWidgets.QApplication.translate("MainWindow", "Typical Workflow", None ))
        self.actionColorize.setText(QtWidgets.QApplication.translate("MainWindow", "Colorize Reviewer Choices", None ))
        self.actionAbstractLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum abstracts per reviewer", None ))
        self.actionAbstractLowerLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Minimum abstracts per reviewer", None ))
        self.actionReviewerLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Minimum reviewers per abstract", None ))
        self.actionReviewerUpperLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum reviewers per abstract", None ))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

